
services:
  bot:
    container_name: bot
    build: 
      context: .
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
        
    networks:
      - botnet
    command: python bot.py

  
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password 
      - POSTGRES_USER=postgres 
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - botnet

networks:
  botnet:
    driver: bridge
volumes:
  postgres_data: